import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'
import classNames from 'classnames'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={classNames([inter.className, "flex justify-center"])}>
        <main className='w-full sm:w-[640px] md:w-[768px] lg:w-[1244px]'>
          {children}
        </main>
      </body>
    </html>
  )
}
